# Generated by Django 4.1.2 on 2022-10-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0004_card_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='comment_SUP',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
