# Generated by Django 4.1.2 on 2022-10-19 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0005_card_comment_sup'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='last_download',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
