# Generated by Django 4.1.2 on 2022-10-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0006_config_last_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='id_kpi',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
