# Generated by Django 4.1.2 on 2022-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0007_card_id_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id_kpi',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
