# Generated by Django 4.1.2 on 2022-10-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0008_alter_card_id_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='kpi_kls2',
            field=models.TextField(null=True),
        ),
    ]
