# Generated by Django 4.1.2 on 2022-10-20 19:30

import apps.balancingapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0011_alter_card_comment_audit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='id_kpi',
            field=models.PositiveIntegerField(verbose_name=apps.balancingapp.models.Card),
        ),
    ]
