# Generated by Django 4.0.2 on 2022-10-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0012_alter_change_id_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='passport',
            field=models.FileField(blank=True, default='', null=True, upload_to='passports/', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='change',
            name='id_kpi',
            field=models.PositiveIntegerField(),
        ),
    ]
