# Generated by Django 4.0.2 on 2022-10-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0013_alter_card_passport_alter_change_id_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='delete',
            field=models.BooleanField(default=0),
        ),
    ]
