# Generated by Django 4.0.2 on 2022-11-04 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0014_card_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='passport',
            field=models.FileField(blank=True, default='', null=True, upload_to='passports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Согласован'), (1, 'Согласование СУП'), (2, 'Отклонён'), (3, 'На доработке'), (4, 'Новый'), (5, 'Корректировка СУП')], default=4),
        ),
    ]
