# Generated by Django 4.0.2 on 2022-11-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancingapp', '0015_alter_card_passport_alter_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status_for_display',
            field=models.CharField(choices=[('Согласован', 'Согласован'), ('Согласование СУП', 'Согласование СУП'), ('Отклонён', 'Отклонён'), ('На доработке', 'На доработке'), ('Новый', 'Новый'), ('Корректировка СУП', 'Корректировка СУП')], default='На доработке', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='passport',
            field=models.FileField(blank=True, default='', null=True, upload_to='passports/', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Согласован'), (1, 'Согласование СУП'), (2, 'Отклонён'), (3, 'На доработке'), (4, 'Новый'), (5, 'Корректировка СУП')], default=4),
        ),
    ]
